import { MenuItem, Location, SaleTransaction, WasteRecord } from "./types/models";
import { findLocationById, findMenuItemByName, binarySearchLocationByCapacity } from "./utils/search";
import {
  sortLocationsByCapacity,
  filterActiveLocations,
  filterMenuItemsByCategory,
  sortMenuItemsByPrice,
  filterSalesByDateRange,
} from "./utils/collections";
import {
  calculateDailyRevenue,
  calculateLocationMargin,
  calculateWasteCost,
  convertCurrency,
  scoreLocationPerformance,
  rankLocationsByPerformance,
  countSalesByPaymentMethod,
  calculateAverageTicket,
  findTopSellingItems,
  groupWasteByReason,
  calculateCountryComparison,
  findExtremeSales,
  findExtremeLocationRevenue,
} from "./utils/transformations";
import { validateMenuItem, validateSaleTransaction, validateLocation } from "./utils/validations";

// ---- Ítems de menú (cubren las 5 categorías de MenuCategory) ----
export const sampleMenuItems: MenuItem[] = [
  {
    id: "ITEM-PICANHA-250",
    name: "Picanha 250g",
    category: "Meat",
    basePrice: { USD: 18.5, COP: 74000 },
    ingredientCost: { USD: 7.2, COP: 28800 },
    prepTimeMinutes: 15,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-FRIES",
    name: "Papas Fritas",
    category: "Side",
    basePrice: { USD: 4.5, COP: 18000 },
    ingredientCost: { USD: 1.2, COP: 4800 },
    prepTimeMinutes: 8,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-COKE",
    name: "Coca-Cola",
    category: "Beverage",
    basePrice: { USD: 2.5, COP: 10000 },
    ingredientCost: { USD: 0.8, COP: 3200 },
    prepTimeMinutes: 2,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-TRESLECHES",
    name: "Tres Leches",
    category: "Dessert",
    basePrice: { USD: 6.0, COP: 24000 },
    ingredientCost: { USD: 2.1, COP: 8400 },
    prepTimeMinutes: 5,
    isAvailableInColombia: true,
    isAvailableInUSA: false,
    allergens: ["Lácteos", "Huevo"],
    status: "Active",
  },
  {
    id: "ITEM-COMBO-FAMILIAR",
    name: "Combo Familiar",
    category: "Combo",
    basePrice: { USD: 42.0, COP: 168000 },
    ingredientCost: { USD: 16.5, COP: 66000 },
    prepTimeMinutes: 25,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Seasonal",
  },
  {
    id: "ITEM-COSTILLA",
    name: "Costilla BBQ",
    category: "Meat",
    basePrice: { USD: 22.5, COP: 90000 },
    ingredientCost: { USD: 9.0, COP: 36000 },
    prepTimeMinutes: 30,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-CHORIZO",
    name: "Chorizo parrillero",
    category: "Meat",
    basePrice: { USD: 7.5, COP: 30000 },
    ingredientCost: { USD: 2.8, COP: 11200 },
    prepTimeMinutes: 12,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-POLLO-BRASA",
    name: "Pollo a la brasa",
    category: "Meat",
    basePrice: { USD: 16.0, COP: 64000 },
    ingredientCost: { USD: 6.2, COP: 24800 },
    prepTimeMinutes: 25,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-LOMO",
    name: "Lomo a la parrilla",
    category: "Meat",
    basePrice: { USD: 19.5, COP: 78000 },
    ingredientCost: { USD: 7.8, COP: 31200 },
    prepTimeMinutes: 20,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-MORCILLA",
    name: "Morcilla artesanal",
    category: "Meat",
    basePrice: { USD: 6.5, COP: 26000 },
    ingredientCost: { USD: 2.4, COP: 9600 },
    prepTimeMinutes: 12,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-JUGO-NATURAL",
    name: "Jugo natural de maracuyá",
    category: "Beverage",
    basePrice: { USD: 4.0, COP: 16000 },
    ingredientCost: { USD: 1.3, COP: 5200 },
    prepTimeMinutes: 5,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-CERVEZA-ARTESANAL",
    name: "Cerveza artesanal",
    category: "Beverage",
    basePrice: { USD: 7.0, COP: 28000 },
    ingredientCost: { USD: 2.5, COP: 10000 },
    prepTimeMinutes: 2,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: ["Gluten"],
    status: "Active",
  },
  {
    id: "ITEM-LIMONADA",
    name: "Limonada de la casa",
    category: "Beverage",
    basePrice: { USD: 3.5, COP: 14000 },
    ingredientCost: { USD: 1.0, COP: 4000 },
    prepTimeMinutes: 4,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-YUCA-FRITA",
    name: "Yuca frita",
    category: "Side",
    basePrice: { USD: 4.0, COP: 16000 },
    ingredientCost: { USD: 1.1, COP: 4400 },
    prepTimeMinutes: 10,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-FLAN-CARAMELO",
    name: "Flan de caramelo",
    category: "Dessert",
    basePrice: { USD: 5.0, COP: 20000 },
    ingredientCost: { USD: 1.7, COP: 6800 },
    prepTimeMinutes: 5,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: ["Lácteos", "Huevo"],
    status: "Active",
  },
];

// ---- Ubicaciones (2 por país) ----
export const sampleLocations: Location[] = [
  // Medellín
  { id: "LOC-MEDELLIN-01", name: "Brasaland El Poblado", city: "Medellín", country: "Colombia", openingYear: 2008, seatingCapacity: 80, staffCount: 12, monthlyRentCost: { USD: 1500, COP: 6000000 }, averageMonthlyUtilities: { USD: 400, COP: 1600000 }, manager: "Carlos Jiménez", status: "Active" },
  { id: "LOC-MEDELLIN-02", name: "Brasaland Laureles", city: "Medellín", country: "Colombia", openingYear: 2011, seatingCapacity: 65, staffCount: 10, monthlyRentCost: { USD: 1300, COP: 5200000 }, averageMonthlyUtilities: { USD: 350, COP: 1400000 }, manager: "Daniela Ruiz", status: "Active" },
  { id: "LOC-MEDELLIN-03", name: "Brasaland Envigado", city: "Medellín", country: "Colombia", openingYear: 2013, seatingCapacity: 70, staffCount: 11, monthlyRentCost: { USD: 1400, COP: 5600000 }, averageMonthlyUtilities: { USD: 380, COP: 1520000 }, manager: "Felipe Vélez", status: "Active" },
  { id: "LOC-MEDELLIN-04", name: "Brasaland Sabaneta", city: "Medellín", country: "Colombia", openingYear: 2016, seatingCapacity: 55, staffCount: 9, monthlyRentCost: { USD: 1100, COP: 4400000 }, averageMonthlyUtilities: { USD: 300, COP: 1200000 }, manager: "Valentina Ospina", status: "Active" },

  // Bogotá
  { id: "LOC-BOGOTA-01", name: "Brasaland Usaquén", city: "Bogotá", country: "Colombia", openingYear: 2014, seatingCapacity: 60, staffCount: 10, monthlyRentCost: { USD: 1800, COP: 7200000 }, averageMonthlyUtilities: { USD: 450, COP: 1800000 }, manager: "Laura Peña", status: "Active" },
  { id: "LOC-BOGOTA-02", name: "Brasaland Chapinero", city: "Bogotá", country: "Colombia", openingYear: 2017, seatingCapacity: 50, staffCount: 9, monthlyRentCost: { USD: 1700, COP: 6800000 }, averageMonthlyUtilities: { USD: 420, COP: 1680000 }, manager: "Andrés Lozano", status: "Active" },
  { id: "LOC-BOGOTA-03", name: "Brasaland Zona Rosa", city: "Bogotá", country: "Colombia", openingYear: 2019, seatingCapacity: 75, staffCount: 13, monthlyRentCost: { USD: 2200, COP: 8800000 }, averageMonthlyUtilities: { USD: 500, COP: 2000000 }, manager: "Camila Torres", status: "Active" },

  // Cali
  { id: "LOC-CALI-01", name: "Brasaland Granada", city: "Cali", country: "Colombia", openingYear: 2015, seatingCapacity: 55, staffCount: 9, monthlyRentCost: { USD: 1200, COP: 4800000 }, averageMonthlyUtilities: { USD: 320, COP: 1280000 }, manager: "Juan Pablo Rengifo", status: "Active" },
  { id: "LOC-CALI-02", name: "Brasaland Ciudad Jardín", city: "Cali", country: "Colombia", openingYear: 2018, seatingCapacity: 60, staffCount: 10, monthlyRentCost: { USD: 1250, COP: 5000000 }, averageMonthlyUtilities: { USD: 330, COP: 1320000 }, manager: "Isabel Victoria", status: "Active" },
  { id: "LOC-CALI-03", name: "Brasaland Unicentro", city: "Cali", country: "Colombia", openingYear: 2020, seatingCapacity: 65, staffCount: 11, monthlyRentCost: { USD: 1350, COP: 5400000 }, averageMonthlyUtilities: { USD: 360, COP: 1440000 }, manager: "Esteban Gómez", status: "Temporarily closed" },

  // Miami
  { id: "LOC-MIAMI-01", name: "Brasaland Brickell", city: "Miami", country: "USA", openingYear: 2018, seatingCapacity: 100, staffCount: 15, monthlyRentCost: { USD: 5500, COP: 22000000 }, averageMonthlyUtilities: { USD: 800, COP: 3200000 }, manager: "Jake Morrison", status: "Active" },
  { id: "LOC-MIAMI-02", name: "Brasaland Coral Gables", city: "Miami", country: "USA", openingYear: 2021, seatingCapacity: 90, staffCount: 14, monthlyRentCost: { USD: 5200, COP: 20800000 }, averageMonthlyUtilities: { USD: 750, COP: 3000000 }, manager: "Amanda Reyes", status: "Active" },

  // Orlando
  { id: "LOC-ORLANDO-01", name: "Brasaland Downtown", city: "Orlando", country: "USA", openingYear: 2021, seatingCapacity: 70, staffCount: 11, monthlyRentCost: { USD: 4200, COP: 16800000 }, averageMonthlyUtilities: { USD: 650, COP: 2600000 }, manager: "Sofía Ramírez", status: "Under renovation" },
  { id: "LOC-ORLANDO-02", name: "Brasaland International Drive", city: "Orlando", country: "USA", openingYear: 2022, seatingCapacity: 85, staffCount: 13, monthlyRentCost: { USD: 4600, COP: 18400000 }, averageMonthlyUtilities: { USD: 700, COP: 2800000 }, manager: "Michael Torres", status: "Active" },
];

// ---- Ventas (cubren los 4 métodos de pago) ----
export const sampleSales: SaleTransaction[] = [
  {
    id: "TXN-2024-15482",
    locationId: "LOC-MEDELLIN-01",
    itemId: "ITEM-PICANHA-250",
    quantity: 2,
    totalPrice: { USD: 37.0, COP: 148000 },
    paymentMethod: "Credit card",
    timestamp: new Date("2024-03-15T19:30:00"),
    waiterName: "María González",
  },
  {
    id: "TXN-2024-15483",
    locationId: "LOC-MIAMI-01",
    itemId: "ITEM-FRIES",
    quantity: 3,
    totalPrice: { USD: 13.5, COP: 54000 },
    paymentMethod: "Cash",
    timestamp: new Date("2024-03-15T20:15:00"),
    waiterName: "John Smith",
  },
  {
    id: "TXN-2024-15484",
    locationId: "LOC-BOGOTA-01",
    itemId: "ITEM-COMBO-FAMILIAR",
    quantity: 1,
    totalPrice: { USD: 42.0, COP: 168000 },
    paymentMethod: "Debit card",
    timestamp: new Date("2024-03-16T13:10:00"),
    waiterName: "Andrés Lozano",
  },
  {
    id: "TXN-2024-15485",
    locationId: "LOC-MEDELLIN-01",
    itemId: "ITEM-COKE",
    quantity: 4,
    totalPrice: { USD: 10.0, COP: 40000 },
    paymentMethod: "Digital wallet",
    timestamp: new Date("2024-03-16T14:00:00"),
    waiterName: "María González",
  },
  {
    id: "TXN-2024-15486",
    locationId: "LOC-MIAMI-01",
    itemId: "ITEM-TRESLECHES",
    quantity: 2,
    totalPrice: { USD: 12.0, COP: 48000 },
    paymentMethod: "Credit card",
    timestamp: new Date("2024-03-17T21:05:00"),
    waiterName: "Jake Morrison",
  },
];

// ---- Registros de desperdicio ----
export const sampleWasteRecords: WasteRecord[] = [
  {
    id: "WASTE-0001",
    locationId: "LOC-MEDELLIN-01",
    itemId: "ITEM-PICANHA-250",
    quantity: 2,
    reason: "Expired",
    cost: { USD: 14.4, COP: 57600 },
    timestamp: new Date("2024-03-14T08:00:00"),
    reportedBy: "Carlos Jiménez",
  },
  {
    id: "WASTE-0002",
    locationId: "LOC-MIAMI-01",
    itemId: "ITEM-FRIES",
    quantity: 5,
    reason: "Cooking error",
    cost: { USD: 6.0, COP: 24000 },
    timestamp: new Date("2024-03-15T12:30:00"),
    reportedBy: "Jake Morrison",
  },
  {
    id: "WASTE-0003",
    locationId: "LOC-BOGOTA-01",
    itemId: "ITEM-TRESLECHES",
    quantity: 3,
    reason: "Customer return",
    cost: { USD: 6.3, COP: 25200 },
    timestamp: new Date("2024-03-16T19:45:00"),
    reportedBy: "Laura Peña",
  },
];

// ---- Exponer todo para el panel HTML ----
(window as any).Brasaland = {
  sampleMenuItems,
  sampleLocations,
  sampleSales,
  sampleWasteRecords,

  // search
  findLocationById,
  findMenuItemByName,
  binarySearchLocationByCapacity,

  // collections
  sortLocationsByCapacity,
  filterActiveLocations,
  filterMenuItemsByCategory,
  sortMenuItemsByPrice,
  filterSalesByDateRange,

  // transformations
  calculateDailyRevenue,
  calculateLocationMargin,
  calculateWasteCost,
  convertCurrency,
  scoreLocationPerformance,
  rankLocationsByPerformance,
  countSalesByPaymentMethod,
  calculateAverageTicket,
  findTopSellingItems,
  groupWasteByReason,
  calculateCountryComparison,
  findExtremeSales,
  findExtremeLocationRevenue,

  // validations
  validateMenuItem,
  validateSaleTransaction,
  validateLocation,
};